import { L } from "@Core/Localization/Localization";
import {
    __countries_ad,
    __countries_ae,
    __countries_af,
    __countries_ag,
    __countries_ai,
    __countries_al,
    __countries_am,
    __countries_an,
    __countries_ao,
    __countries_ar,
    __countries_as,
    __countries_at,
    __countries_au,
    __countries_aw,
    __countries_az,
    __countries_ba,
    __countries_bb,
    __countries_bd,
    __countries_be,
    __countries_bf,
    __countries_bg,
    __countries_bh,
    __countries_bi,
    __countries_bj,
    __countries_bm,
    __countries_bn,
    __countries_bo,
    __countries_br,
    __countries_bs,
    __countries_bt,
    __countries_bv,
    __countries_bw,
    __countries_by,
    __countries_bz,
    __countries_ca,
    __countries_cd,
    __countries_cf,
    __countries_cg,
    __countries_ch,
    __countries_ci,
    __countries_ck,
    __countries_cl,
    __countries_cm,
    __countries_cn,
    __countries_co,
    __countries_cr,
    __countries_cu,
    __countries_cv,
    __countries_cy,
    __countries_cz,
    __countries_de,
    __countries_dj,
    __countries_dk,
    __countries_dm,
    __countries_do,
    __countries_dz,
    __countries_ec,
    __countries_ee,
    __countries_eg,
    __countries_eh,
    __countries_er,
    __countries_es,
    __countries_et,
    __countries_fi,
    __countries_fj,
    __countries_fk,
    __countries_fm,
    __countries_fo,
    __countries_fr,
    __countries_ga,
    __countries_gb,
    __countries_gd,
    __countries_ge,
    __countries_gf,
    __countries_gg,
    __countries_gh,
    __countries_gi,
    __countries_gl,
    __countries_gm,
    __countries_gn,
    __countries_gp,
    __countries_gq,
    __countries_gr,
    __countries_gs,
    __countries_gt,
    __countries_gu,
    __countries_gw,
    __countries_gy,
    __countries_hk,
    __countries_hm,
    __countries_hn,
    __countries_hr,
    __countries_ht,
    __countries_hu,
    __countries_id,
    __countries_ie,
    __countries_il,
    __countries_im,
    __countries_in,
    __countries_io,
    __countries_iq,
    __countries_ir,
    __countries_is,
    __countries_it,
    __countries_je,
    __countries_jm,
    __countries_jo,
    __countries_jp,
    __countries_ke,
    __countries_kg,
    __countries_kh,
    __countries_ki,
    __countries_km,
    __countries_kn,
    __countries_kp,
    __countries_kr,
    __countries_kw,
    __countries_ky,
    __countries_kz,
    __countries_la,
    __countries_lb,
    __countries_lc,
    __countries_li,
    __countries_lk,
    __countries_lr,
    __countries_ls,
    __countries_lt,
    __countries_lu,
    __countries_lv,
    __countries_ly,
    __countries_ma,
    __countries_mc,
    __countries_md,
    __countries_me,
    __countries_mg,
    __countries_mh,
    __countries_mk,
    __countries_ml,
    __countries_mm,
    __countries_mn,
    __countries_mo,
    __countries_mp,
    __countries_mq,
    __countries_mr,
    __countries_ms,
    __countries_mt,
    __countries_mu,
    __countries_mv,
    __countries_mw,
    __countries_mx,
    __countries_my,
    __countries_mz,
    __countries_na,
    __countries_nc,
    __countries_ne,
    __countries_nf,
    __countries_ng,
    __countries_ni,
    __countries_nl,
    __countries_no,
    __countries_np,
    __countries_nr,
    __countries_nu,
    __countries_nz,
    __countries_om,
    __countries_pa,
    __countries_pe,
    __countries_pf,
    __countries_pg,
    __countries_ph,
    __countries_pk,
    __countries_pl,
    __countries_pm,
    __countries_pn,
    __countries_pr,
    __countries_ps,
    __countries_pt,
    __countries_pw,
    __countries_py,
    __countries_qa,
    __countries_re,
    __countries_ro,
    __countries_rs,
    __countries_ru,
    __countries_rw,
    __countries_sa,
    __countries_sb,
    __countries_sc,
    __countries_sd,
    __countries_se,
    __countries_sg,
    __countries_sh,
    __countries_si,
    __countries_sk,
    __countries_sl,
    __countries_sm,
    __countries_sn,
    __countries_so,
    __countries_sr,
    __countries_st,
    __countries_sv,
    __countries_sy,
    __countries_sz,
    __countries_tc,
    __countries_td,
    __countries_tf,
    __countries_tg,
    __countries_th,
    __countries_tj,
    __countries_tk,
    __countries_tl,
    __countries_tm,
    __countries_tn,
    __countries_to,
    __countries_tr,
    __countries_tt,
    __countries_tv,
    __countries_tw,
    __countries_tz,
    __countries_ua,
    __countries_ug,
    __countries_um,
    __countries_us,
    __countries_uy,
    __countries_uz,
    __countries_va,
    __countries_vc,
    __countries_ve,
    __countries_vg,
    __countries_vi,
    __countries_vn,
    __countries_vu,
    __countries_wf,
    __countries_ws,
    __countries_ye,
    __countries_yt,
    __countries_za,
    __countries_zm,
    __countries_zw
} from "@Strings/_strings";

export default function(): Array<[string, string]> {
    return [
        ["ad", L(__countries_ad)],
        ["ae", L(__countries_ae)],
        ["af", L(__countries_af)],
        ["ag", L(__countries_ag)],
        ["ai", L(__countries_ai)],
        ["al", L(__countries_al)],
        ["am", L(__countries_am)],
        ["an", L(__countries_an)],
        ["ao", L(__countries_ao)],
        ["ar", L(__countries_ar)],
        ["as", L(__countries_as)],
        ["at", L(__countries_at)],
        ["au", L(__countries_au)],
        ["aw", L(__countries_aw)],
        ["az", L(__countries_az)],
        ["ba", L(__countries_ba)],
        ["bb", L(__countries_bb)],
        ["bd", L(__countries_bd)],
        ["be", L(__countries_be)],
        ["bf", L(__countries_bf)],
        ["bg", L(__countries_bg)],
        ["bh", L(__countries_bh)],
        ["bi", L(__countries_bi)],
        ["bj", L(__countries_bj)],
        ["bm", L(__countries_bm)],
        ["bn", L(__countries_bn)],
        ["bo", L(__countries_bo)],
        ["br", L(__countries_br)],
        ["bs", L(__countries_bs)],
        ["bt", L(__countries_bt)],
        ["bv", L(__countries_bv)],
        ["bw", L(__countries_bw)],
        ["by", L(__countries_by)],
        ["bz", L(__countries_bz)],
        ["ca", L(__countries_ca)],
        ["cd", L(__countries_cd)],
        ["cf", L(__countries_cf)],
        ["cg", L(__countries_cg)],
        ["ch", L(__countries_ch)],
        ["ci", L(__countries_ci)],
        ["ck", L(__countries_ck)],
        ["cl", L(__countries_cl)],
        ["cm", L(__countries_cm)],
        ["cn", L(__countries_cn)],
        ["co", L(__countries_co)],
        ["cr", L(__countries_cr)],
        ["cu", L(__countries_cu)],
        ["cv", L(__countries_cv)],
        ["cy", L(__countries_cy)],
        ["cz", L(__countries_cz)],
        ["de", L(__countries_de)],
        ["dj", L(__countries_dj)],
        ["dk", L(__countries_dk)],
        ["dm", L(__countries_dm)],
        ["do", L(__countries_do)],
        ["dz", L(__countries_dz)],
        ["ec", L(__countries_ec)],
        ["ee", L(__countries_ee)],
        ["eg", L(__countries_eg)],
        ["eh", L(__countries_eh)],
        ["er", L(__countries_er)],
        ["es", L(__countries_es)],
        ["et", L(__countries_et)],
        ["fi", L(__countries_fi)],
        ["fj", L(__countries_fj)],
        ["fk", L(__countries_fk)],
        ["fm", L(__countries_fm)],
        ["fo", L(__countries_fo)],
        ["fr", L(__countries_fr)],
        ["ga", L(__countries_ga)],
        ["gb", L(__countries_gb)],
        ["gd", L(__countries_gd)],
        ["ge", L(__countries_ge)],
        ["gf", L(__countries_gf)],
        ["gg", L(__countries_gg)],
        ["gh", L(__countries_gh)],
        ["gi", L(__countries_gi)],
        ["gl", L(__countries_gl)],
        ["gm", L(__countries_gm)],
        ["gn", L(__countries_gn)],
        ["gp", L(__countries_gp)],
        ["gq", L(__countries_gq)],
        ["gr", L(__countries_gr)],
        ["gs", L(__countries_gs)],
        ["gt", L(__countries_gt)],
        ["gu", L(__countries_gu)],
        ["gw", L(__countries_gw)],
        ["gy", L(__countries_gy)],
        ["hk", L(__countries_hk)],
        ["hm", L(__countries_hm)],
        ["hn", L(__countries_hn)],
        ["hr", L(__countries_hr)],
        ["ht", L(__countries_ht)],
        ["hu", L(__countries_hu)],
        ["id", L(__countries_id)],
        ["ie", L(__countries_ie)],
        ["il", L(__countries_il)],
        ["im", L(__countries_im)],
        ["in", L(__countries_in)],
        ["io", L(__countries_io)],
        ["iq", L(__countries_iq)],
        ["ir", L(__countries_ir)],
        ["is", L(__countries_is)],
        ["it", L(__countries_it)],
        ["je", L(__countries_je)],
        ["jm", L(__countries_jm)],
        ["jo", L(__countries_jo)],
        ["jp", L(__countries_jp)],
        ["ke", L(__countries_ke)],
        ["kg", L(__countries_kg)],
        ["kh", L(__countries_kh)],
        ["ki", L(__countries_ki)],
        ["km", L(__countries_km)],
        ["kn", L(__countries_kn)],
        ["kp", L(__countries_kp)],
        ["kr", L(__countries_kr)],
        ["kw", L(__countries_kw)],
        ["ky", L(__countries_ky)],
        ["kz", L(__countries_kz)],
        ["la", L(__countries_la)],
        ["lb", L(__countries_lb)],
        ["lc", L(__countries_lc)],
        ["li", L(__countries_li)],
        ["lk", L(__countries_lk)],
        ["lr", L(__countries_lr)],
        ["ls", L(__countries_ls)],
        ["lt", L(__countries_lt)],
        ["lu", L(__countries_lu)],
        ["lv", L(__countries_lv)],
        ["ly", L(__countries_ly)],
        ["ma", L(__countries_ma)],
        ["mc", L(__countries_mc)],
        ["md", L(__countries_md)],
        ["me", L(__countries_me)],
        ["mg", L(__countries_mg)],
        ["mh", L(__countries_mh)],
        ["mk", L(__countries_mk)],
        ["ml", L(__countries_ml)],
        ["mm", L(__countries_mm)],
        ["mn", L(__countries_mn)],
        ["mo", L(__countries_mo)],
        ["mp", L(__countries_mp)],
        ["mq", L(__countries_mq)],
        ["mr", L(__countries_mr)],
        ["ms", L(__countries_ms)],
        ["mt", L(__countries_mt)],
        ["mu", L(__countries_mu)],
        ["mv", L(__countries_mv)],
        ["mw", L(__countries_mw)],
        ["mx", L(__countries_mx)],
        ["my", L(__countries_my)],
        ["mz", L(__countries_mz)],
        ["na", L(__countries_na)],
        ["nc", L(__countries_nc)],
        ["ne", L(__countries_ne)],
        ["nf", L(__countries_nf)],
        ["ng", L(__countries_ng)],
        ["ni", L(__countries_ni)],
        ["nl", L(__countries_nl)],
        ["no", L(__countries_no)],
        ["np", L(__countries_np)],
        ["nr", L(__countries_nr)],
        ["nu", L(__countries_nu)],
        ["nz", L(__countries_nz)],
        ["om", L(__countries_om)],
        ["pa", L(__countries_pa)],
        ["pe", L(__countries_pe)],
        ["pf", L(__countries_pf)],
        ["pg", L(__countries_pg)],
        ["ph", L(__countries_ph)],
        ["pk", L(__countries_pk)],
        ["pl", L(__countries_pl)],
        ["pm", L(__countries_pm)],
        ["pn", L(__countries_pn)],
        ["pr", L(__countries_pr)],
        ["ps", L(__countries_ps)],
        ["pt", L(__countries_pt)],
        ["pw", L(__countries_pw)],
        ["py", L(__countries_py)],
        ["qa", L(__countries_qa)],
        ["re", L(__countries_re)],
        ["ro", L(__countries_ro)],
        ["rs", L(__countries_rs)],
        ["ru", L(__countries_ru)],
        ["rw", L(__countries_rw)],
        ["sa", L(__countries_sa)],
        ["sb", L(__countries_sb)],
        ["sc", L(__countries_sc)],
        ["sd", L(__countries_sd)],
        ["se", L(__countries_se)],
        ["sg", L(__countries_sg)],
        ["sh", L(__countries_sh)],
        ["si", L(__countries_si)],
        ["sk", L(__countries_sk)],
        ["sl", L(__countries_sl)],
        ["sm", L(__countries_sm)],
        ["sn", L(__countries_sn)],
        ["so", L(__countries_so)],
        ["sr", L(__countries_sr)],
        ["st", L(__countries_st)],
        ["sv", L(__countries_sv)],
        ["sy", L(__countries_sy)],
        ["sz", L(__countries_sz)],
        ["tc", L(__countries_tc)],
        ["td", L(__countries_td)],
        ["tf", L(__countries_tf)],
        ["tg", L(__countries_tg)],
        ["th", L(__countries_th)],
        ["tj", L(__countries_tj)],
        ["tk", L(__countries_tk)],
        ["tl", L(__countries_tl)],
        ["tm", L(__countries_tm)],
        ["tn", L(__countries_tn)],
        ["to", L(__countries_to)],
        ["tr", L(__countries_tr)],
        ["tt", L(__countries_tt)],
        ["tv", L(__countries_tv)],
        ["tw", L(__countries_tw)],
        ["tz", L(__countries_tz)],
        ["ua", L(__countries_ua)],
        ["ug", L(__countries_ug)],
        ["um", L(__countries_um)],
        ["us", L(__countries_us)],
        ["uy", L(__countries_uy)],
        ["uz", L(__countries_uz)],
        ["va", L(__countries_va)],
        ["vc", L(__countries_vc)],
        ["ve", L(__countries_ve)],
        ["vg", L(__countries_vg)],
        ["vi", L(__countries_vi)],
        ["vn", L(__countries_vn)],
        ["vu", L(__countries_vu)],
        ["wf", L(__countries_wf)],
        ["ws", L(__countries_ws)],
        ["ye", L(__countries_ye)],
        ["yt", L(__countries_yt)],
        ["za", L(__countries_za)],
        ["zm", L(__countries_zm)],
        ["zw", L(__countries_zw)]
    ];
}
