var localized_strings,
localization_promise = (function (){
    var deferred = new $.Deferred();
    localized_strings_default = {
        empty_wishlist: "Empty Wishlist",
        purchase_date: "(Purchased __date__)",
        options: "Options",
        website: "Website",
        contribute: "Contribute (GitHub)",
		store: "Store",
		community: "Community",
		news: "News",
		about: "About",
		donate: "Donate",
		language: "Language",
		highlight: "Highlight",
		options_owned: "Items You Own",
		options_wishlist: "Items On Your Wishlist",
		options_coupon: "Items With Coupons",
		options_gift: "Items Stored As Gift",
		options_guest: "Items You Have A Guest Pass For",
		options_friends_wishlist: "Items Your Friends Have Wishlisted",
		options_hide_install: "Hide \"Install Steam\" button in header",
		options_drm: "Show 3rd Party DRM Warnings",
		options_lowestprice: "Show Price History Information",
		options_metacritic: "Show Metacritic User Scores",
		options_steamdb: "Show SteamDB Links",
		options_wsgf: "Show WSGF (Widescreen) Info",
		options_carousel_description: "Show App Descriptions On Storefront Carousel",
		options_profile_links: "Show profile links to",
		options_total_spent: "Show \"Total Spent\" on Account Page",
		options_group_events: "Show Events on Group Overview",
		options_greenlight_banner: "Replace Steam Greenlight Banner",
		tag: "Tag",
		theworddefault: "Default",
		save: "Save",
		saved: "Saved",
        clear_cache: "Clear cached data",
        forums: "Forums",
        coupon_available: "You have a coupon available!",
        coupon_application_note: "A coupon in your inventory will be applied automatically at checkout.",
        coupon_learn_more: "<a href=\"https://support.steampowered.com/kb_article.php?ref=4210-YIPC-0275\">Learn more</a> about Steam Coupons",
        add_to_cart: "Add to Cart",
        drm_third_party: "Warning: This title uses 3rd party DRM",
        empty_cart: "Empty Cart",
        events_view_all: "VIEW ALL",
        events: "Events",
        dlc_data_header: "Downloadable Content Details",
        tag_owned: "Owned",
        tag_wishlist: "Wishlist",
        tag_coupon: "Coupon",
        tag_inv_gift: "Gift",
        tag_inv_guestpass: "Guestpass",
        tag_friends_want: "<a href=\"http://steamcommunity.com/my/friendsthatplay/__appid__\">__friendcount__ wish for</a>"
    };

    localized_strings = {
        "en": localized_strings_default,
        "ar":       {},
        "cs":       {},
        "da":       {},
        "de":       {},
        "el":       {},
        "es":       {
			empty_wishlist: "Lista de Deseos vacia",
			purchase_date: "(Compro __date__)",
			website: "Sitio web",
			contribute: "Contribuir (GitHub)",
			options: "Opciones",
			store: "Tienda",
			community: "Comunidad",
			news: "Noticias",
			about: "Sobre",
			donate: "Donar",
			language: "Idioma",
			highlight: "Destacar",
			options_owned: "Articulos usted el propietario",
			options_wishlist: "Articulos en su lista de deseos",
			options_coupon: "Articulos con Cupones",
			options_gift: "Articulos almacenados como un regalo",
			options_guest: "Articulos que tienen pases de invitado",
			options_friends_wishlist: "Articulos por su amigos lista de deseos",
			options_hide_install: "Ocultar Boton de \"Install Steam\" en el encabezado",
			options_drm: "Mostrar 3rd Party DRM Advertencias",
			options_lowestprice: "Mostrar Precio Historia Informacion",
			options_metacritic: "Mostrar Metacritic puntuaciones de los usuarios",
			options_wsgf: "Mostrar WSGF Informacion con pantalla grande",
			options_carousel_description: "Mostrar la informacion en la aplicacion del carrusel Escaparate",
			options_profile_links: "Mostrar enlaces a la pagina de perfil",
			options_total_spent: "Mostrar total en la cuenta de la pagina",
			options_group_events: "Mostrar eventos de Revision de grupo",
			options_greenlight_banner: "Reemplace Bandera de Steam Greenlight",
			tag: "Etiqueta",
			theworddefault: "Defecto",
			save: "Guardar",
			saved: "Guardado",
			clear_cache: "Datos claros en cache",
			forums: "Foros",
			coupon_available: "Usted tiene un cupon disponible!",
			coupon_application_note: "Un cupon en su inventario se aplicara automaticamente momento de pagar.",
			coupon_learn_more: "<a href=\"https://support.steampowered.com/kb_article.php?ref=4210-YIPC-0275\">Mas informacion</a> sobre cupones de Steam",
			add_to_cart: "Anadir al carro",
			drm_third_party: "Advertencia: Este titulo utiliza 3rd party DRM",
			empty_cart: "Vaciar Carro",
			events_view_all: "VER TODOS",
			events: "Eventos",
			dlc_data_header: "Contenido Descargable Detalles",
			tag_owned: "Poseido",
			tag_wishlist: "Lista de deseos",
			tag_coupon: "Cupon",
			tag_inv_gift: "Regalo",
			tag_inv_guestpass: "Pase Invitado",
			tag_friends_want: "<a href=\"http://steamcommunity.com/my/friendsthatplay/__appid__\">__friendcount__ amigos deseen</a>"
		},
        "fi":       {},
        "fr":       {},
        "hu":       {},
        "it":       {},
        "ja":       {},
        "ko":       {},
        "nl":       {
            empty_wishlist: "Verlanglijst leegmaken",
            purchase_date: "(Gekocht op __date__)",
            options: "Opties",
            website: "Website",
            contribute: "Bijdragen (GitHub)",
            clear_cache: "Gecachete data verwijderen",
            forums: "Forums",
            coupon_available: "Je hebt een waardebon beschikbaar!",
            coupon_application_note: "Een coupon in je inventaris wordt automatisch toegepast bij het afrekenen.",
            coupon_learn_more: "<a href=\"https://support.steampowered.com/kb_article.php?ref=4210-YIPC-0275\">Kom meer te weten</a> over Steam-coupons",
            add_to_cart: "Aan winkelwagen toevoegen",
            drm_third_party: "Waarschuwing: Dit programma maakt gebruik van DRM van derden",
            empty_cart: "Winkelwagen leegmaken",
            events_view_all: "ALLES BEKIJKEN",
            events: "Evenementen",
            dlc_data_header: "Details over downloadbare inhoud",
            tag_owned: "In je bezit",
            tag_wishlist: "Verlanglijst",
            tag_coupon: "Waardebon",
            tag_inv_gift: "Geschenk",
            tag_inv_guestpass: "Gastenpas",
            tag_friends_want: "<a href=\"http://steamcommunity.com/my/friendsthatplay/__appid__\">__friendcount__ willen dit</a>"
        },
        "no":       {},
        "pl":       {},
        "pt":       {},
        "pt-br":    {},
        "ro":       {},
        "ru":       {},
        "sv":       {},
        "th":       {},
        "tr":       {},
        "zh-hans":  {},
        "zh-hant":  {}
    };

    // Set english defaults.
    $.each(localized_strings, function(lang, strings){
        $.each(localized_strings_default, function(key, val){
            if (!strings[key]) strings[key] = val;
        });
    });
    setTimeout(deferred.resolve, 250); // Delay ever so slightly to make sure all loc is loaded.
    return deferred.promise();
})();