
export default Object.freeze({
    "ACCOUNT": 1,
    "APP": 2,
    "BUNDLE": 3,
    "STORE_DEFAULT": 4,
    "FUNDS": 5,
    "REGISTER_KEY": 6,
    "SALE": 7,
    "SEARCH": 8,
    "STATS": 9,
    "STORE_FRONT": 10,
    "SUB": 11,
    "WISHLIST": 12,
    "AGECHECK": 13,
    "COMMUNITY_DEFAULT": 14,
    "WORKSHOP": 15,
    "PROFILE_ACTIVITY": 16,
    "GAMES": 17,
    "PROFILE_EDIT": 18,
    "BADGES": 19,
    "GAME_CARD": 20,
    "FRIENDS_THAT_PLAY": 21,
    "FRIENDS": 22, // unused
    "GROUPS": 23, // unused
    "INVENTORY": 24,
    "MARKET_LISTING": 25,
    "MARKET": 26,
    "PROFILE_HOME": 27,
    "GROUP_HOME": 28,
    "GUIDES": 29,
    "COMMUNITY_APP": 30,
    "COMMUNITY_STATS": 31,
    "MY_WORKSHOP": 32,
    "SHARED_FILES": 33,
    "WORKSHOP_BROWSE": 34,
    "EDIT_GUIDE": 35,
    "RECOMMENDED": 36,
    "BOOSTER_CREATOR": 37,
    "TRADE_OFFER": 38,
    "FRIENDS_AND_GROUPS": 39,
});

