export {ErrorParser} from "./Core/Errors/ErrorParser";
export {Errors} from "./Core/Errors/Errors";
export {HTML} from "./Core/Html/Html";
export {HTMLParser} from "./Core/Html/HtmlParser";
export {default as Language} from "./Core/Localization/Language";
export {default as Localization} from "./Core/Localization/Localization";
export {CookieStorage} from "./Core/Storage/CookieStorage";
export {default as LocalStorage} from "./Core/Storage/LocalStorage";
export {default as SyncedStorage} from "./Core/Storage/SyncedStorage";
export {BackgroundSimple} from "./Core/BackgroundSimple";
export {StringUtils} from "./Core/Utils/StringUtils";
export {TimeUtils} from "./Core/Utils/TimeUtils";
export {Debug} from "./Core/Debug";
export {Downloader} from "./Core/Downloader";
export {Environment} from "./Core/Environment";
export {default as ExtensionResources} from "./Core/ExtensionResources";
export {GameId} from "./Core/GameId";
export {Info} from "./Core/Info";
export {PermissionOptions, Permissions} from "./Core/Permissions";
export {Version} from "./Core/Version";
